
import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chugr010
 */
public class JFrameMainMenu extends javax.swing.JFrame 
{
    /**
     * Creates new form JFrameMainMenu
     */
    public JFrameMainMenu() 
    {
        initComponents();
        
        // set the background image on the form
        try
        {
            Image img = ImageIO.read(new File("Background.jpg"));
            BackgroundPanel backPanel = new BackgroundPanel(img, BackgroundPanel.SCALED, 1.0f, 0.5f);
            getContentPane().add(backPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, this.getWidth(), this.getHeight()));
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Login Screen", JOptionPane.WARNING_MESSAGE);
        }
        
        // center the form on the screen
        this.setLocationRelativeTo(null);

        // make the form non-resizeable
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonPlayGame = new javax.swing.JButton();
        jButtonRules = new javax.swing.JButton();
        jButtonLeaderBoard = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cooltext215249365635443.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jButtonPlayGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_play-game (1).png"))); // NOI18N
        jButtonPlayGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayGameActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 150, 40));

        jButtonRules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_rules.png"))); // NOI18N
        jButtonRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRulesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 310, 100, 40));

        jButtonLeaderBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_leaderboard.png"))); // NOI18N
        jButtonLeaderBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeaderBoardActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLeaderBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 170, 40));

        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_exit (1).png"))); // NOI18N
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 80, 40));

        jButtonRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/button_register (1).png"))); // NOI18N
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRulesActionPerformed
        JFrameRules r = new JFrameRules();
        r.setVisible(true);
    }//GEN-LAST:event_jButtonRulesActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed

        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonLeaderBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeaderBoardActionPerformed
        // TODO add your handling code here:
        JFrameScoreBoard frm = new JFrameScoreBoard();
        frm.setVisible(true);
    }//GEN-LAST:event_jButtonLeaderBoardActionPerformed

    private void jButtonPlayGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayGameActionPerformed
        // TODO add your handling code here:
        JFrameGameSelection frm = new JFrameGameSelection();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPlayGameActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        JFrameRegister frameMakeUser = new JFrameRegister();
        frameMakeUser.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonLeaderBoard;
    private javax.swing.JButton jButtonPlayGame;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonRules;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
